In [1]:
from pennystockpipeline.PennyStockData import PennyStockData
import numpy as np
import pandas as pd

## Testing
table_name = "all_historical_modified"
database_name_with_path = "mod_historicaldata.db"

#print(database_name_with_path)
#print(database_name_with_path.strip())

psd = PennyStockData(database_name_with_path, table_name, drop_discrete_columns=True, impute=True, row_data_threshold=12, format='numpy_sequence', verbose=2)
tickers = psd.tickers
#print(tickers)

data = psd.data
df = pd.DataFrame(data, columns=psd.headers)
df.head()

dataset = psd.numpy_sequence
print(len(dataset))

[INFO][PennyStockData]: mod_historicaldata.db exists
[INFO][PennyStockData]: SQlite connected with mod_historicaldata.db
[INFO][PennyStockData]: SQlite executed query SELECT ROWID, ticker_id, ticker, p_date, p_time, volume_weighted_average, open, close, high, low, time FROM all_historical_modified WHERE 1 ORDER BY ticker_id, p_date, p_time
[DEBUG][PennyStockData]: headers: ['id', 'ticker_id', 'ticker', 'p_date', 'p_time', 'volume_weighted_average', 'open', 'close', 'high', 'low', 'time']
[DEBUG][PennyStockData]: len(data): > 549609
[INFO][PennyStockData]: SQlite executed query SELECT id, ticker FROM tickers WHERE 1 ORDER BY id
[INFO][PennyStockData]: Records have been numpied successfully on the variable dataset
33


In [ ]:
#print(f'tickers_count {len(dataset)}')
#for i in range(len(dataset)):
#    print(len(dataset[i]))

data = psd.data
df = pd.DataFrame(data, columns=psd.headers)
df.head()


In [ ]:
t_data = np.transpose(data)
#[print(x) for i, x in enumerate(data) if i < 5]
## The idea is to create an array such that dataset has structure [ticker_id][p_date][(col0, col1, col2, ..., coln),(col0, col1, col2, ..., coln)]
## here (col0, col1, col2, ..., coln) is the sequence data as a list of tuples from each row having 5 mins interval data 
## (refer imputing for missing data)

## Let's first get the list of tickers
tickers = np.array(psd.tickers)

#print(np.where(t_data[1] == (str)(tickers[0][0])))
#indices = np.where(t_data[1] == (str)(tickers[0][0]))
#print(data[indices])

data = np.array(psd.data)
tickers_data = {}
#print(data[:,3])
#print(data[:,1])
#sum = 0
for ticker in tickers:
    ticker_indices = np.where(t_data[1] == (str)(ticker[0]))
    ticker_data = data[ticker_indices]
    ticker_dates = np.unique(ticker_data[:,3])

    ticker_dates_data = {}
    
    for ticker_date in ticker_dates:
        ticker_date_indices = np.where(ticker_data[:,3] == (str)(ticker_date))
        ticker_date_data = data[ticker_date_indices]
        
        ticker_dates_data[ticker_date] = ticker_date_data
    tickers_data[ticker[0]] = ticker_dates_data

#print(tickers_data[2]['2022-07-12'])
    #print(tickers_dates)
    #print(len(ticker_data))
    #sum = sum + len(ticker_data)
#    print(np.where((str)(ticker[0]) in data[:,1]))
    #print(data[(str)(ticker[0]) in data[:,1]])
    #print(data[,:1] == (str)(ticker[0]))
    #print(data[0:-1])
    #ticker_data_indices = np.where(t_data[1] == (str)(ticker[0]))[0]
    #ticker_data_indices.append(np.where(t_data[1] == (str)(ticker[0]))[0])
    #print(np.array(np.where((t_data[1] == (str)(ticker[0])))))
    #ticker_data_indices.append(np.array(np.where((t_data[1] == (str)(ticker[0])))))
    #x = data.
    #print(t_data[np.where(t_data[1] == (str)(ticker[0]))])
    #for a in enumerate(np.where(t_data[1] == (str)(ticker[0]))[0]):
    #    ticker_dates = np.unique(t_data[3]
#print (sum)
#for ticker_data_index in ticker_data_indices:
    

#print(ticker_data_indices)



In [ ]:
'''
(array([    0,     1,     2, ..., 26648, 26649, 26650], dtype=int64),)
(array([26651, 26652, 26653, ..., 57240, 57241, 57242], dtype=int64),)
(array([57243, 57244, 57245, ..., 85936, 85937, 85938], dtype=int64),)
(array([ 85939,  85940,  85941, ..., 111874, 111875, 111876], dtype=int64),)
(array([111877, 111878, 111879, ..., 146890, 146891, 146892], dtype=int64),)
(array([146893, 146894, 146895, ..., 168120, 168121, 168122], dtype=int64),)
(array([168123, 168124, 168125, ..., 201751, 201752, 201753], dtype=int64),)
(array([201754, 201755, 201756, ..., 229565, 229566, 229567], dtype=int64),)
(array([229568, 229569, 229570, ..., 311756, 311757, 311758], dtype=int64),)
(array([311759, 311760, 311761, ..., 323717, 323718, 323719], dtype=int64),)
'''

In [ ]:
# #data = psd.data

#data

#data_by_ticker = {}
#for ticker in tickers:
#    data_by_ticker[ticker] = data[data['ticker'] == ticker].copy()

#for t in range(len(tickers)):
#    t_data[t-1] = data[data[0] == tickers[t-1]].copy()

#data[data[j] for t in tickers for j in psd.size if psd.data[j][0] == t]

#for ticker in tickers.unique():
#    data_by_ticker[ticker] = data[data['ticker'] == ticker].copy()
#    data_by_ticker[ticker]['normalized_volume_weighted_average'] = data_by_ticker[ticker]['volume_weighted_average'] / data_by_ticker[ticker]['volume_weighted_average'].max() #Normalized closing price data

#t_data = []
#3k = 0
#for t in tickers:
#    for j in range(k, psd.size):
#        if (t == data[j][0]):
#            t_data[t][j] = (data[j])
#        else:
#            k = j
#            break

#print(len(t_data))
#for t in tickers:
#    tickers_data = [[np.where(np.transpose(psd.data)[0] == t) for t in tickers] for j in range(psd.size)]
#    print(tickers_data)
#    break
#ticker_data = [np.where(self.data[0] == t) for t in tickers]
#tickers = np.unique(data[0])
#print(tickers)
#print(data[0])
#print(data[1])
#print(data[2])
#print(tickers)
## [(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]
#t_data = [x_data(t).append(data[j]) for j in range(psd.size) for t in tickers if data[j][0]==t]

#t_data = data[np.where([(data[k][0]==t) for k in range(psd.size) for t in tickers])]

#t_data = data[np.where([(data[k][0]==t) for k in range(5) for t in tickers])]

#print(t_data[0])


#t_data = np.transpose(data)
#print(t_data[0])
#print(len(t_data))
#x = np.where(([[data[j][0] == t for j in range(len(data))] for t in tickers]), data[j])

#for j in range(len(data)):
#    for t in tickers:
#        if (t_data[j] == t):
#            print(t)

#x = np.where([[t_data[j] == t] for j in range(len(data)) for t in tickers], t_data[j])
#print(len(x))

In [ ]:
#tickers_data = {}
#tickers_dates_data = {}
#l = 0

#for t in tickers:
#    ticker_data = []
#    ticker_dates = []
#    for k in range(psd.size):
#        if (t == data[k][1]):
#            if (data[k][2] not in ticker_dates):
#                ticker_data = np.array(ticker_data)
#                tickers_data[t][ticker_dates[len(ticker_dates)-1]] = ticker_data
#                ticker_data = []
#                ticker_dates.append(data[k][2])
#            ticker_data.append(data[k])
            #ticker_data[data[k][2]].append(data[k])
                
            #if p_date == 0 || p_date == data[k][2]:
            #    p_date = data[k][2]
            #    ticker_data.append(data[k])
            #else:
            #    p_date = data[k][2]
            #    tickers_data[t][p_date] = ticker_data[p_date].append(data[k])
            #ticker_data.append(data[k])
#        else:
#            l = k
    
    #ticker_data = np.array(ticker_data)
    #tickers_data[t] = ticker_data

#for ticker_data in tickers_data:
#    ticker_dates = np.unique(np.transpose(ticker_data)[2])
#    ticker_date_data = []
#    for m in range(len(ticker_dates)):
#        ticker_date_data.append
    
#print(len(tickers_data))